### ISSUE TITLE
Why does SqlServer transport configuration set TimeoutManager to 'disabled'

### ISSUE THREAD

**Issue by trevorreeves** [rebus-org/Rebus.SqlServer#25]
I'm trying to understand this line:

https://github.com/rebus-org/Rebus.SqlServer/blob/2254c3c35d8d335308ccab787f96638bb76c2431/Rebus.SqlServer/Config/SqlServerTransportConfigurationExtensions.cs#L186

The consequence being, when I configure a SqlServer Transport, then configure SqlServer Timeouts using the provided config extension method, I get an exception as there is already a primary Timeout manager set.

**Comment by mookid8000** [comment]
Oh, it's because there's no need for a SQL Server timeout manager, because the SQL Server transport natively supports delayed messages. 😄 

E.g. look [here](https://github.com/rebus-org/Rebus.SqlServer/blob/2254c3c35d8d335308ccab787f96638bb76c2431/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L375-L422) to see how a message gets its visibility delay set, depending on the `rbs2-deferred-until` header.
