### ISSUE TITLE
The "recipient" is missing in 5.0.5

### ISSUE THREAD

**Issue by davidtabatadze** [rebus-org/Rebus.SqlServer#44]
Hey there.

I have just updated my `Rebus.SqlServer` from version `4.0.0` to `5.0.5`.
It appears that `UseSqlServer` function misses the parameter that was creating `recipient` cloumn in corresponding table.
Old code `UseSqlServer("connection string", "table name", "recipient name")` is now invalid.
New code `UseSqlServer("connection string", "table name")` is creating table without `recipient `column.

Is this "recipient feature" forbidden or is it put somewhere else in configuration?

**Comment by mookid8000** [comment]
It's because v5 of Rebus.SqlServer uses separate tables to model queues. This has the advantage that one long queue does not impact the performance of all other queues.

Therefore, the second argument to the configuration method is actually the bus' own input queue name:
```csharp
.Transport(t => t.UseSqlServer(connectionString, "my-queue"))
```

As you might have noticed, this will create a table called `[my-queue]`, from which this particular bus instance will receive its messages.

I hope that makes sense 😄
