### ISSUE TITLE
[Question] Deleteing audits past threshold

### ISSUE THREAD

**Issue by macchmie3** [rebus-org/Rebus.SqlServer#68]
Is there any way to automatically clean up audit messages?
I specify auditing with following method when configuring rebus:

`options.EnableMessageAuditing("audit-queue-name");`

My problem is that I run a process to browse some audit messages. I only care about the most recent one, and all past, let's say 7-14 days is obsolete to me and I would like to have it removed. Of course I know that I can clean up audits by myself, but I'm wondering about built-in ways :)

**Comment by mookid8000** [comment]
Unfortunately, there's no built-in way to do this.

And in most cases, it's not even possible, because most queueing systems don't have an API that can filter messages like that.

One way of using the "forward audited messages to a specific queue" is to create a Rebus endpoint, which will save the messages into a database – this way, audited messages can be cleaned up in any way you like.

Rebus' [transport message forwarding](https://github.com/rebus-org/Rebus/wiki/Transport-message-forwarding) capability is a great way to do that, because it's a pretty slim and performant way of processing raw messages.
